CREATE DATABASE RaceDayDB;
GO



CREATE TABLE [USER] (
    UserID INT IDENTITY PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE ORGANIZER (
    OrganizerID INT IDENTITY PRIMARY KEY,
    UserID INT UNIQUE NOT NULL,
    OrganizationName VARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES [USER](UserID)
);

CREATE TABLE PARTICIPANT (
    ParticipantID INT IDENTITY PRIMARY KEY,
    UserID INT UNIQUE NOT NULL,
    DateOfBirth DATE NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES [USER](UserID)
);

CREATE TABLE CATEGORY (
    CategoryID INT IDENTITY PRIMARY KEY,
    CategoryName VARCHAR(100) UNIQUE NOT NULL,
    Description VARCHAR(255),
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE EVENT (
    EventID INT IDENTITY PRIMARY KEY,
    OrganizerID INT NOT NULL,
    CategoryID INT NOT NULL,
    EventName VARCHAR(100) NOT NULL,
    EventDate DATETIME NOT NULL,
    Location VARCHAR(100) NOT NULL,
    Description VARCHAR(255),
    MaxParticipants INT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (OrganizerID) REFERENCES ORGANIZER(OrganizerID),
    FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

CREATE TABLE ENROLLMENT (
    EnrollmentID INT IDENTITY PRIMARY KEY,
    EventID INT NOT NULL,
    ParticipantID INT NOT NULL,
    EnrollmentDate DATETIME DEFAULT GETDATE(),
    Status VARCHAR(20) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (EventID) REFERENCES EVENT(EventID),
    FOREIGN KEY (ParticipantID) REFERENCES PARTICIPANT(ParticipantID),
    UNIQUE (EventID, ParticipantID)
);

CREATE TABLE RESULT (
    ResultID INT IDENTITY PRIMARY KEY,
    EnrollmentID INT UNIQUE NOT NULL,
    Position INT NOT NULL,
    FinishTime TIME NOT NULL,
    ResultStatus VARCHAR(20) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (EnrollmentID) REFERENCES ENROLLMENT(EnrollmentID)
);
GO